# 配置迁移至七彩石
runmode: PRODUCTION
forcel5: false
ormdebug: false
database:
    driver: mysql
    source: ""
redis:
    address: 127.0.0.1:6379
    password: ""
prometheus:
    gateway:
    - https://prom.ee.myssl.com:9095
    echourl: http://127.0.0.1:8089/latest/meta-data
    open: true
    cert: conf/certs/client.pem
    key: conf/certs/client.key
etcd:
    endpoints:
    - http://192.168.252.41:2379
    echourl: http://127.0.0.1:8089/latest/meta-data
    cacert: conf/etcd/ca.pem
    cert: conf/etcd/cert.pem
    key: conf/etcd/key.pem

myssl:
    domain:
    id:
    key:
    anaapi:
    detectioncount: 40
# dnsnodes:
#     - locationcode: "86"
#       addr: 10.112.65.55
#       name: 中国大陆Slave
#       supportedns: false
#       level: 1
qcloud:
    notifygateway: http://message.tencentyun.com:50011
    accountgateway: http://account.tencentyun.com:50001
    module: sslpod
    caller: "sslpod"
    themeids:
        - 2452
    env: "idc"
# define app
backend:
    listen: 20000
    basicauth:
        qcloud:
    basicplan: 15958
    task:
        duration: 6 # count
        interval: 5
    logpath: /data/release/sslpod/backend.log
checker:
    listen: 20010
    basicauth:
        backend:
    task:
        fastworker: 160 # one cpu config
        fasttimeout: 12 # /s
        fullworker: 15 # one cpu config
        fulltimeout: 120 # /s
    logpath: /data/release/sslpod/checker.log
notifier:
    listen: 20020
    logpath: /data/release/sslpod/notifier.log
    ratelimit: 5000
polaris:
    polarisnamespace: Production
    backend:
        service: sslpod.backend
        port: 20000
        token: 
    checker:
        service: sslpod.checker
        port: 20010
        token: 
    notifier:
        service: sslpod.notifier
        port: 20020
        token: 
kafka:
    topic: needCheckDomains
    sasl:
        username: ckafka-yjrzbr5z#sslpod-production
        password: 
        instanceid:
    servers:
        - ''
    consumergroupid:
