version: '3'
services:
    echoip:
        image: harbor.trustasia.cn/mysslee/qcloud-echoip:dev
        ports:
            - 8089:8089
        restart: always
        logging:
            options:
                max-size: "500m"
                max-file: "5"
