FROM csighub.tencentyun.com/sslpod/tlinux-go1.15:v1.0 AS builder

COPY . /data/release/newsslpod/
RUN cd /data/release/newsslpod/app/backend \
    && go build -o backend -mod vendor

FROM csighub.tencentyun.com/sslpod/tlinux-go1.15:v1.0

COPY --from=builder /data/release/newsslpod/app/backend/backend /data/release/newsslpod/backend
COPY --from=builder /data/release/newsslpod/conf /data/release/newsslpod/conf/
CMD ["/data/release/newsslpod/backend"]
