FROM csighub.tencentyun.com/sslpod/tlinux-go1.15:v1.0 AS builder

COPY . /data/release/newsslpod/
RUN cd /data/release/newsslpod/app/checker \
    && go build -o checker -mod vendor

FROM csighub.tencentyun.com/sslpod/tlinux-go1.15:v1.0

COPY --from=builder /data/release/newsslpod/app/checker/checker /data/release/newsslpod/checker
COPY --from=builder /data/release/newsslpod/conf /data/release/newsslpod/conf/
CMD ["/data/release/newsslpod/checker"]
