basePath: /api
definitions:
  message.Message:
    properties:
      code:
        type: integer
      data:
        type: object
      error:
        type: string
    type: object
host: localhost:20020
info:
  contact:
    email: henry.chen@trustasia.com
    name: henry.chen
  description: 为 qcloud 提供 openapi 功能.
  license: {}
  title: MySSL EE Notifier API
  version: "1.0"
paths:
  /app/infos:
    get:
      consumes:
      - multipart/form-data
      description: app信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.Message'
      summary: app 相关信息
      tags:
      - 内部调用
swagger: "2.0"
