basePath: /api
definitions:
  message.Message:
    properties:
      code:
        type: integer
      data:
        type: object
      error:
        type: string
    type: object
  model.AccountShow:
    properties:
      createdAt:
        type: string
      name:
        type: string
      plan:
        type: PlanInfo
      status:
        type: integer
    type: object
  model.CertInfoShow:
    properties:
      beginTime:
        type: string
      brand:
        type: string
      certType:
        type: string
      cn:
        type: string
      days:
        type: integer
      endTime:
        type: string
      hash:
        type: string
      issuer:
        type: string
      keyAlgo:
        type: string
      sans:
        type: string
      trustStatus:
        type: string
    type: object
  qcloud.ResponseBack:
    properties:
      response:
        type: object
    type: object
  services.NoticeInfo:
    properties:
      id:
        type: integer
      limitInfos:
        type: string
      noticeType:
        type: integer
    type: object
  services.Paging:
    properties:
      allowMaxAddDomain:
        description: 允许添加域名总数
        type: integer
      allowMonitoringCount:
        description: 允许的监控数量
        type: integer
      currentMonitoringCount:
        description: 当前监控的数量
        type: integer
      result:
        description: 结果
        type: object
      searchTotal:
        description: 搜索出来的数量
        type: integer
      total:
        description: 总数
        type: integer
    type: object
host: localhost:20000
info:
  contact:
    email: henry.chen@trustasia.com
    name: henry.chen
  description: 为 qcloud 提供 openapi 功能.
  license: {}
  title: MySSL EE Backend API
  version: "1.0"
paths:
  /app/infos:
    get:
      consumes:
      - multipart/form-data
      description: app信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/message.Message'
      summary: app 相关信息
      tags:
      - 内部调用
  /certs:
    get:
      consumes:
      - application/json
      description: 获取已经添加域名的证书
      parameters:
      - description: DescribeCerts
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      - description: 偏移量
        in: query
        name: Offset
        required: true
        type: integer
      - description: 数量
        in: query
        name: Limit
        required: true
        type: integer
      - description: 搜索的类型，可选：domainId,commonName,hash
        enum:
        - domainId
        - commonName
        - hash
        in: query
        name: Search
        type: string
      - description: 搜索类型的值
        in: query
        name: Target
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg.Data
          schema:
            items:
              $ref: '#/definitions/model.CertInfoShow'
            type: array
      summary: 证书列表
      tags:
      - SSL证书
  /dashboard:
    get:
      consumes:
      - multipart/form-data
      description: 获取图表dashboard数据
      parameters:
      - description: DescribeDashboard
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: json string
          schema:
            type: string
      summary: dashboard图表
      tags:
      - 监控面板
  /domains:
    post:
      consumes:
      - application/json
      description: 通过域名端口添加监控, 0 web, 1 smtp, 2 imap, 3 pops
      parameters:
      - description: CreateDomain
        in: formData
        name: action
        required: true
        type: string
      - description: sslpod
        in: formData
        name: serviceType
        required: true
        type: string
      - description: 监控的服务器类型
        enum:
        - 0
        - 1
        - 2
        - 3
        in: formData
        name: ServerType
        required: true
        type: integer
      - description: 添加的域名
        in: formData
        name: Domain
        required: true
        type: string
      - description: 添加的端口
        in: formData
        name: Port
        required: true
        type: string
      - description: 指定域名的IP，可选
        in: formData
        name: IP
        type: string
      - description: 是否开启通知告警
        in: formData
        name: Notice
        type: boolean
      - description: 给域名添加标签，多个以逗号隔开
        in: formData
        name: Tags
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qcloud.ResponseBack'
      summary: 添加监控域名
      tags:
      - 监控管理
  /domains/{domainId}:
    delete:
      consumes:
      - application/json
      description: 通过域名ID删除
      parameters:
      - description: DeleteDomain
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      - description: 域名列表中的ID
        in: path
        name: DomainId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qcloud.ResponseBack'
      summary: 删除监控的域名
      tags:
      - 监控管理
  /domains/cert/{DomainId}:
    get:
      consumes:
      - multipart/form-data
      description: 获取域名关联证书
      parameters:
      - description: DescribeDomainCerts
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      - description: 域名ID
        in: path
        name: DomainId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg.Data
          schema:
            items:
              $ref: '#/definitions/model.CertInfoShow'
            type: array
      summary: 获取域名关联证书
      tags:
      - 监控管理
  /domains/notice/{domainId}:
    put:
      consumes:
      - application/json
      description: 域名是否需要通知
      parameters:
      - description: ChangeDomainSwitch
        in: formData
        name: action
        required: true
        type: string
      - description: sslpod
        in: formData
        name: serviceType
        required: true
        type: string
      - description: 域名列表中的ID
        in: path
        name: DomainId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qcloud.ResponseBack'
      summary: 域名通知开关
      tags:
      - 监控管理
  /domains/refresh/{domainId}:
    put:
      consumes:
      - multipart/form-data
      description: 强制刷新域名检测
      parameters:
      - description: RefreshDomain
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      - description: 域名列表中的ID
        in: path
        name: DomainId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qcloud.ResponseBack'
      summary: 刷新域名
      tags:
      - 监控管理
  /domains/resolve:
    get:
      consumes:
      - multipart/form-data
      description: 解析域名获取IP地址
      parameters:
      - description: ResolveDomain
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      - description: 解析的域名
        in: query
        name: Domain
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg.Data
          schema:
            items:
              type: string
            type: array
      summary: 解析域名，获取IP
      tags:
      - 监控管理
  /domains/search:
    post:
      consumes:
      - application/json
      description: 通过searchType搜索已经添加的域名, 这里逻辑比较复杂
      parameters:
      - description: DescribeDomains
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      - description: 偏移量
        in: query
        name: Offset
        required: true
        type: integer
      - description: 获取数量
        in: query
        name: Limit
        required: true
        type: integer
      - description: 搜索的类型
        enum:
        - none
        - tags
        - grade
        - brand
        - code
        - hash
        - limit
        in: query
        name: SearchType
        required: true
        type: string
      - description: tag
        in: query
        name: Tag
        type: string
      - description: 等级
        in: query
        name: Grade
        type: string
      - description: 品牌名
        in: query
        name: Brand
        type: string
      - description: 混合搜索
        in: query
        name: Code
        type: string
      - description: 证书hash
        in: query
        name: Hash
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.Paging'
      summary: 搜索域名，域名列表
      tags:
      - 监控管理
  /domains/tags:
    get:
      consumes:
      - multipart/form-data
      description: 获取所有tag
      parameters:
      - description: DescribeDomainTags
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: tag列表
      tags:
      - 监控管理
  /domains/tags/{AccountDomainId}:
    put:
      consumes:
      - multipart/form-data
      description: 改变域名tag
      parameters:
      - description: ModifyDomainTags
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      - description: 域名ID
        in: path
        name: AccountDomainId
        required: true
        type: integer
      - description: 更新后的tag，多个以逗号隔开
        in: formData
        name: Tags
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qcloud.ResponseBack'
      summary: 改变域名tag
      tags:
      - 监控管理
  /notice/info:
    get:
      consumes:
      - multipart/form-data
      description: 获取通知信息
      parameters:
      - description: DescribeNoticeInfo
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: msg.Data, limit_infos中的type可能为:limit_email,limit_wechat,limit_phone
          schema:
            $ref: '#/definitions/services.NoticeInfo'
      summary: 获取通知信息
      tags:
      - 通知告警
  /notice/switch:
    put:
      consumes:
      - multipart/form-data
      description: '通知类型更改，用二进制进行表示: 001微信，010短信，100邮箱。对应二进制位，如果是1代表开启,0代表关闭'
      parameters:
      - description: ModifyNoticeType
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      - description: '通知开关的二进制: 1 微信|2 短信|4 邮件'
        in: formData
        name: Type
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/qcloud.ResponseBack'
      summary: 更改通知类型
      tags:
      - 通知告警
  /plan/{uin}:
    get:
      consumes:
      - multipart/form-data
      description: account plan
      parameters:
      - description: 账户ID
        in: path
        name: uin
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: get account plan or refresh
      tags:
      - 内部调用
  /profile:
    get:
      consumes:
      - application/json
      description: account profile
      parameters:
      - description: DescribeProfile
        in: query
        name: action
        required: true
        type: string
      - description: sslpod
        in: query
        name: serviceType
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.AccountShow'
      summary: get account profile
      tags:
      - 账户信息
swagger: "2.0"
